/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


#define RCC_CR  	(*(volatile uint32_t *)0x40021000)
#define	RCC_CFGR        (*(volatile uint32_t *)0x40021004)
#define	RCC_APB2ENR     (*(volatile uint32_t *)0x40021018)
#define	RCC_AHBENR      (*(volatile uint32_t *)0x40021014)
#define GPIOA_CRL       (*(volatile uint32_t *)0x40010800)
#define GPIOA_CRH       (*(volatile uint32_t *)0x40010804)
#define FLASH_ACR       (*(volatile uint32_t *)0x40022000)
#define USART_SR        (*(volatile uint32_t *)0x40013800)
#define USART_DR        (*(volatile uint32_t *)0x40013804)
#define USART_BRR       (*(volatile uint32_t *)0x40013808)
#define USART_CR1       (*(volatile uint32_t *)0x4001380C)
#define SYST_CSR        (*(volatile uint32_t *)0xE000E010)
#define SYST_RVR        (*(volatile uint32_t *)0xE000E014)
#define SYST_CVR        (*(volatile uint32_t *)0xE000E018)
#define ADC1_SR         (*(volatile uint32_t *)0x40012400)
#define ADC1_CR2        (*(volatile uint32_t *)0x40012408)
#define ADC1_SMPR2      (*(volatile uint32_t *)0x40012410)
#define ADC1_SQR1       (*(volatile uint32_t *)0x4001242C)
#define ADC1_SQR3       (*(volatile uint32_t *)0x40012434)
#define ADC1_DR         (*(volatile uint32_t *)0x4001244C)



#define F_CPU 64000000
#define BAUD_RATE 9600



 void SystemClock_Config(void);
 void USART1_Init(void);
 void USART1_BaudRate(void);
 void USART1_SendString(const char *str);
 void USART1_SendChar(char c);
 void delay_ms(uint32_t ms);
 void SysTick_Init(void);
 void ADC_Init(void);
 uint16_t ADC1_Read(void);



 void SystemClock_Config(void) {
  RCC_CR |= (1<<0);
  while(!(RCC_CR & (1<<1)));
  FLASH_ACR |= (1 << 1);
  FLASH_ACR |=(1<<4);
  while(!(FLASH_ACR & (1<<5)));
  RCC_CFGR &= ~(1<<16);
  RCC_CFGR |= (1<<18)|(1<<19)|(1<<20)|(1<<21);
  RCC_CR |= (1<<24);
  while(!(RCC_CR & (1<<25)));
  RCC_CFGR |= (1<<1);
  while(!(RCC_CFGR & (1<<3)));
  RCC_CFGR &= ~((1<<7)|(1<<10)|(1<<13));
  RCC_AHBENR |= (1<<10);


 }

 void SysTick_Init(void) {
 	SYST_RVR = 8000 - 1;
 	SYST_CVR = 0;
 	SYST_CSR &= ~(1 << 2);
 	SYST_CSR |= (1<<0);
 }
 void delay_ms(uint32_t ms) {
 SYST_CVR = 0;
 	for (uint32_t i = 0; i < ms; i++) {
 	        while (!(SYST_CSR & (1 << 16)));
     }
 }

 void USART1_Init(void){
 	RCC_APB2ENR |=(1<<2)|(1<<14);
 	GPIOA_CRH |=(1<<4)|(1<<5)|(1<<7)|(1<<10);
 	GPIOA_CRH &= ~((1<<6)|(1<<8)|(1<<9)|(1<<11));
 	USART1_BaudRate();
    USART_CR1 |= (1 << 13) | (1 << 3) | (1 << 2)|(1<<5);
    USART_CR1 &= ~(1 << 10);

 }
 void USART1_BaudRate(void){
	     uint32_t USARTDIV = F_CPU/(16*BAUD_RATE);
	 	 uint32_t mantissa = (uint32_t)USARTDIV;
	 	 uint32_t fraction = (uint32_t)((USARTDIV-mantissa)*16);
	 	 USART_BRR = (mantissa<<4)|fraction;

 }
 void USART1_SendChar(char c) {
     USART_DR = c;
     while (!(USART_SR & (1 << 7)));
     while (!(USART_SR & (1 << 6)));

 }
 void USART1_SendString(const char *str) {
     while (*str) {
         USART1_SendChar(*str++);
     }
 }

 uint16_t ADC1_Read(void) {
     ADC1_CR2 |= (1 << 22);
     while (!(ADC1_SR & (1 << 1)));
     return ADC1_DR;
 }
 void ADC_Init(void){
	 RCC_APB2ENR |= (1<<9);
	 GPIOA_CRL &= ~(0X0f);
	 ADC1_CR2 |= (1<<17)|(1<<18)|(1<<19)|(1<<1)|(1<<20);
	 ADC1_CR2 &= ~(1<<11);
	 ADC1_SMPR2 |= 0X07;
	 ADC1_SQR3 = 0;
	 ADC1_SQR1 = 0;
	 ADC1_CR2 |= (1 << 0);
	 delay_ms(5);
	 ADC1_CR2 |= (1 << 2);
	 while (ADC1_CR2 & (1 << 2));
	 ADC1_CR2 |= (1 << 3);
	 while (ADC1_CR2 & (1 << 3));


 }
 int main(void){
 	  SystemClock_Config();
      USART1_Init();
      SysTick_Init();
     ADC_Init();
      USART1_SendString("ADC value\r\n");
 	while(1){
 		uint16_t value = ADC1_Read();
 		char buffer[15];
 	    sprintf(buffer, "%u", value);
 	    USART1_SendString(buffer);
 	    USART1_SendString("\r\n");

 	}


 }
