/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define RCC_CR 			 (*(volatile uint32_t *)0x40021000)
#define RCC_CFGR     	 (*(volatile uint32_t *)0x40021004)
#define RCC_APB2ENR      (*(volatile uint32_t *)0x40021018)
#define RCC_AHBENR       (*(volatile uint32_t *)0x40021014)
#define GPIOA_CRL        (*(volatile uint32_t *)0x40010800)
#define GPIOA_CRH        (*(volatile uint32_t *)0x40010804)
#define FLASH_ACR        (*(volatile uint32_t *)0x40022000)
#define RCC_APB1ENR      (*(volatile uint32_t *)0x4002101C)
#define TIM3_CR1         (*(volatile uint32_t *)0x40000400)
#define TIM3_SR          (*(volatile uint32_t *)0x40000410)
#define TIM3_CNT         (*(volatile uint32_t *)0x40000424)
#define TIM3_PSC         (*(volatile uint32_t *)0x40000428)
#define TIM3_ARR         (*(volatile uint32_t *)0x4000042C)
#define TIM3_DIER        (*(volatile uint32_t *)0x4000040C)
#define TIM3_CCMR1       (*(volatile uint32_t *)0x40000418)
#define TIM3_CCER        (*(volatile uint32_t *)0x40000420)
#define TIM3_CCR1        (*(volatile uint32_t *)0x40000434)
#define TIM3_EGR         (*(volatile uint32_t *)0x40000414)
#define SYST_CSR        (*(volatile uint32_t *)0xE000E010)
#define SYST_RVR        (*(volatile uint32_t *)0xE000E014)
#define SYST_CVR        (*(volatile uint32_t *)0xE000E018)




 void SystemClock_Config(void);
 void GPIO_Init(void);
 void TIM3_Capture_Init(void);
 void delay(volatile uint32_t d);
 //void TIM3_IRQHandler(void);
 void delay_ms(uint32_t ms);
 void SysTick_Init(void);



int i=0;
 void SystemClock_Config(void) {
  RCC_CR |= (1<<0);
  while(!(RCC_CR & (1<<1)));
  FLASH_ACR |= (1 << 1);
  FLASH_ACR |=(1<<4);
  while(!(FLASH_ACR & (1<<5)));
  RCC_CFGR &= ~((1<<16)|(1<<8));
  RCC_CFGR |= (1<<18)|(1<<19)|(1<<20)|(1<<21)|(1<<9)|(1<<10);
  RCC_CR |= (1<<24);
  while(!(RCC_CR & (1<<25)));
  RCC_CFGR |= (1<<1);
  while(!(RCC_CFGR & (1<<3)));
  RCC_CFGR &= ~((1<<7)|(1<<10)|(1<<13));
  RCC_AHBENR |= (1<<10);


 }


 void GPIO_Init(void){
 	RCC_APB2ENR |=(1<<2);
    GPIOA_CRL |= (0x09<<24);


 }
 void TIM3_Capture_Init(void){

	 RCC_APB1ENR |= (1 << 1);
	 TIM3_CR1 = 0;
	 TIM3_PSC = 63;
	 TIM3_ARR = 999;
	 TIM3_CCR1 = 0;
	 TIM3_CCMR1 &= ~(0xFF);
	 TIM3_CCMR1 |= (6 << 4);
	 TIM3_CCMR1 |= (1 << 3);
	 TIM3_CCER &= ~(0Xff);
	 TIM3_CCER |= 0x03;
	 TIM3_DIER |= 0X03;
	 TIM3_CR1 |= (1<<7);
	 TIM3_CR1 |= (1 << 0);
	  }

 void SysTick_Init(void) {
 	SYST_RVR = 8000 - 1;
 	SYST_CVR = 0;
 	SYST_CSR &= ~(1 << 2);
 	SYST_CSR |= (1<<0);
 }
 void delay_ms(uint32_t ms) {
 SYST_CVR = 0;
 	for (uint32_t i = 0; i < ms; i++) {
 	        while (!(SYST_CSR & (1 << 16)));
     }
 }



 int main(void){
 	SystemClock_Config();
      GPIO_Init();
      SysTick_Init();
     TIM3_Capture_Init();

	while(1){
		for(int i=0;i<TIM3_ARR;i++){
		 TIM3_CCR1 = i;
		 delay_ms(5);

		}
		for(int i=TIM3_ARR;i>0;i--){
				 TIM3_CCR1 = i;
				 delay_ms(5);

				}

	     }
 }
