/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_CR 			 (*(volatile uint32_t *)0x40021000)
#define RCC_CFGR     	 (*(volatile uint32_t *)0x40021004)
#define RCC_APB2ENR      (*(volatile uint32_t *)0x40021018)
#define RCC_AHBENR       (*(volatile uint32_t *)0x40021014)
#define GPIOC_CRH        (*(volatile uint32_t *)0x40011004)
#define GPIOC_BSRR       (*(volatile uint32_t *)0x40011010)
#define FLASH_ACR        (*(volatile uint32_t *)0x40022000)
#define RCC_APB1ENR      (*(volatile uint32_t *)0x4002101C)
#define TIM3_CR1         (*(volatile uint32_t *)0x40000400)
#define TIM3_SR          (*(volatile uint32_t *)0x40000410)
#define TIM3_CNT         (*(volatile uint32_t *)0x40000424)
#define TIM3_PSC         (*(volatile uint32_t *)0x40000428)
#define TIM3_ARR         (*(volatile uint32_t *)0x4000042C)



 void SystemClock_Config(void);
 void LED_Init(void);
 void TIM3_Init(void);
 void delay_ms(uint16_t ms);


 void SystemClock_Config(void) {
  RCC_CR |= (1<<0);
  while(!(RCC_CR & (1<<1)));
  FLASH_ACR |= (1 << 1);
  FLASH_ACR |=(1<<4);
  while(!(FLASH_ACR & (1<<5)));
  RCC_CFGR &= ~((1<<16)|(1<<8));
  RCC_CFGR |= (1<<18)|(1<<19)|(1<<20)|(1<<21)|(1<<9)|(1<<10);
  RCC_CR |= (1<<24);
  while(!(RCC_CR & (1<<25)));
  RCC_CFGR |= (1<<1);
  while(!(RCC_CFGR & (1<<3)));
  RCC_CFGR &= ~((1<<7)|(1<<10)|(1<<13));
  RCC_AHBENR |= (1<<10);


 }


 void LED_Init(void){
 	RCC_APB2ENR |=(1<<4);
 	GPIOC_CRH |=(1<<20);
 	GPIOC_CRH &= ~((1<<21)|(1<<22)|(1<<23));
 }
 void TIM3_Init(void){

	 RCC_APB1ENR |= (1 << 1);

	 TIM3_PSC = 63999;
	 TIM3_ARR = 10;
     TIM3_CNT = 0;
	 TIM3_CR1 |= (1 << 0);

 }
 void delay_ms(uint16_t ms) {
     while (ms--) {
         TIM3_CNT = 0;
         TIM3_SR &= ~(1 << 0);
         while (!(TIM3_SR & (1 << 0)));
     }
 }

 int main(void){
 	SystemClock_Config();
      LED_Init();
      TIM3_Init();

 	while(1){
 		GPIOC_BSRR =(1<<29);
 		delay_ms(50);
 		GPIOC_BSRR =(1<<13);
        delay_ms(50);


 	}
 }
